# Generated by Django 3.2 on 2023-07-09 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店铺名称')),
                ('province', models.CharField(max_length=100, verbose_name='省(直辖市填写市名)')),
                ('city', models.CharField(max_length=100, verbose_name='市')),
                ('district', models.CharField(max_length=100, verbose_name='区/县')),
                ('street', models.CharField(max_length=100, verbose_name='街道')),
                ('detailed_address', models.CharField(max_length=200, verbose_name='详细地址')),
                ('scale', models.CharField(choices=[('10', '10万以内'), ('30', '10-30万'), ('100', '30-100万'), ('500', '100-500万'), ('1000', '500万以上')], max_length=20, verbose_name='店铺规模')),
                ('community_type', models.CharField(choices=[('T1001', '社区'), ('T1002', '商圈'), ('T1003', '景区'), ('T1004', '办公园区'), ('T1005', '其他')], max_length=20, verbose_name='店铺环境')),
                ('dominant_shop_type', models.CharField(choices=[('M1001', '零售'), ('M1002', '餐饮'), ('M1003', '休闲娱乐'), ('M1004', '服务行业'), ('M1005', '教育培训'), ('M1006', '医疗保健'), ('M1007', '文化艺术'), ('M1009', '服饰'), ('M1008', '其他')], max_length=50, verbose_name='周边主要类型')),
                ('average_house_price', models.CharField(choices=[('5000', '5000以内'), ('10000', '5001-10000'), ('15000', '10001-15000'), ('20000', '15001-20000'), ('25000', '20001-25000'), ('30000', '25001-30000'), ('30001', '30000以上')], max_length=5, verbose_name='周围平均房价')),
            ],
        ),
        migrations.CreateModel(
            name='SurroundingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_type', models.CharField(max_length=100, verbose_name='类型')),
                ('info_name', models.CharField(max_length=100, verbose_name='名称')),
                ('info_address', models.CharField(max_length=200, verbose_name='地址')),
                ('distance', models.FloatField(verbose_name='距离')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop', verbose_name='商店')),
            ],
        ),
        migrations.CreateModel(
            name='ShopType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shoptype')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shoptype', verbose_name='店铺类型'),
        ),
        migrations.AddField(
            model_name='shop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='学校名字')),
                ('student_count', models.CharField(choices=[('1000', '1000以内'), ('2000', '1000-2000'), ('3000', '3000以上')], max_length=20, verbose_name='学生人数')),
                ('school_type', models.CharField(choices=[('kindergarten ', '幼儿园'), ('primary', '小学'), ('secondary', '中学'), ('university', '大学'), ('trade', '职业学校'), ('others', '其他')], max_length=20, verbose_name='学校类型')),
                ('walk_type', models.CharField(choices=[('walk', '走读'), ('live', '住校'), ('mix', '混合')], max_length=20, verbose_name='走读住读')),
                ('shop', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop', verbose_name='店铺')),
            ],
        ),
    ]
