# Generated by Django 3.2 on 2023-07-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('days', models.IntegerField(choices=[(7, '7 days'), (30, '30 days'),
                                                      (60, '60 days'), (90, '90 days'),
                                                      (180, '180 days'), (360, '360 days')], default=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
